### ISSUE TITLE
fail pip install pyLLE

### ISSUE THREAD

**Issue by yumtong** [gregmoille/pyLLE#18]
**Describe the bug**
The pyLLE can't install in cmd.

**To Reproduce**
When Python 3.7.2 and Julia 1.1.1 is installed, in a cmd window (Windows) type: 
pip install pyLLE  Failed.
**Expected behavior**
1)How to install pyLLE ?

**Error or Screenshots**
C:\Users\yumtong>pip install pyLLE
Collecting pyLLE
  Using cached https://files.pythonhosted.org/packages/4e/24/a0247d0b1c7af554425177808db4053a0b0466c7696dd74ed08bae9eadbf/pyLLE-3.0.0.tar.gz
ERROR: Could not install packages due to an EnvironmentError: [Errno 22] Invalid argument: 'C:\\Users\\yumtong\\AppData\\Local\\Temp\\pip-install-vnd6q9d6\\pyLLE\\pyLLE.egg-info/Icon\r'

<img width="722" alt="微信图片_20191010103029" src="https://user-images.githubusercontent.com/55547011/66534523-045f3880-eb49-11e9-972c-b7a2ccc31507.png">
**Desktop (please complete the following information):**
 - Python 3.7.2
 - Julia 1.1.1
**Additional context**

**Comment by gregmoille** [comment]
Thanks for reporting the issue. 
It seems like I left some hidden files hanging around during the twine upload to PyPi. It should have been clean now with the 3.0.1 version. 
Please deleted pip cache install again pyLLE with cache disabled 

```
pip --no-cache-dir install pyLLE
```
