### ISSUE TITLE
How to understand the Main Solver in 'ComputeLLE.jl'?

### ISSUE THREAD

**Issue by yxwroth** [gregmoille/pyLLE#26]
![image](https://user-images.githubusercontent.com/55616517/133100310-fdce8104-1431-419f-851e-cf1cd7860a9e.png)
I met some problems while rewriting the core code in 'ComputeLLE.jl' about the basic Spilt-Step Fourier Method in Main Solver code area.(See Fig.1)

As we known,SSFFT alogrithm obey the following solving method:
![image](https://user-images.githubusercontent.com/55616517/133101118-427a389a-d912-4dde-9286-3c2c60860073.png)
![image](https://user-images.githubusercontent.com/55616517/133101169-28268ed7-d94e-4f4d-9cc3-ff26bf053bc2.png)
The two terms required by the SSFFT method can be obtained by setting the linear term to zero or the nonlinear term to zero respectively.For example:
![fig1](https://user-images.githubusercontent.com/55616517/133103660-a0b6b6f6-86cf-4bc6-b2c3-55e6b7eec8a1.jpg)

However,it is difficult to figure out the original terms in Main Solver of 'ComputeLLE.jl'.Could you please show me the original form of the formula?Thanks a lot.

**Comment by gregmoille** [comment]
That’s a super late answer sorry about that. 
The SSF Fourier you are presenting is a simple one. The error propagation and stability of the solver is not great this way. Usually using a half split step Fourier method provides much better convergence and stability of the solver. The linear term and nonlinear term in the solver are quite self-explanatory: everything with loss and dispersion are linear (i.e. everything the iteration nested loop to find the correct step for the NL propagation), everything that has field mixing is nonlinear (i.e. everything in the iteration nested loop). 
For more info, you could look at Agrawal’s book and his implementation in matlab
