### ISSUE TITLE
A question about TestDispersion.csv.

### ISSUE THREAD

**Issue by syq-nulixuexi** [gregmoille/pyLLE#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by syq-nulixuexi** [comment]
We have successfully run the example, and we want to know how the data in the .csv table is obtained.

**Comment by gregmoille** [comment]
The data available in the example are the resonant frequencies of a ring resonator. To get them, you will need to solve the wave equation in the Fourier domain and find out the eigenvalues of the system - basically a mode solver. Usually done using Comsol, Lumerical, house-made mode solver (Tom Murphy’s wgmode solver in matlab), etc… while taking into account the bend radius of the resonator (i.e. conformal mapping if radius large or need of cylindrical coordinate with Comsol).
