### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by DanHickstein** [gregmoille/pyLLE#35]
Hi Greg and all!

We're just getting started trying to use pyLLE for some microresonator simulations. What's the current state of the project? Should we be attempting to install version 4.0.0, or just keep using the master branch for the time being?

**Comment by gregmoille** [comment]
Hey Dan! 

Good to hear you'll be using pyLLE. I've been slacking for way too long, but I would suggest using version 4.0.0 given there are a lot of improvements, both on the front end (more friendly attributes and so far) and on the back end (extensive comments on the code for tweaking, and dual pumping if needed). 
If you are not too in a rush, I could get you an example + howto by the end of the weekend and merge it to the main branch, which would finally motivate me for this long overdue task.

**Comment by DanHickstein** [comment]
Hi Greg!

Thanks so much for your quick reply. Yeah, if you have time to update the master with the changes in 4.0.0 and add an example and how-to, that would really help get us rolling in the right direction as quickly as possible. Looking forward to trying it! :)

**Comment by gregmoille** [comment]
Hey Dan, 

Took me shorter than anticipated. I merged v4.0.0 to the main branch. I also updated the pypi so the new version can be pip installed. 
I tried to make an extensive example in the jupyter notebook but let me know if you have any questions, happy to help!

**Comment by DanHickstein** [comment]
Awesome! Thank you so much Greg!
