### ISSUE TITLE
Question about format for resonator dispersion

### ISSUE THREAD

**Issue by DanHickstein** [gregmoille/pyLLE#41]
In the example iPython notebook, the dispersion is plotted and the "LLE" dispersion is similar, but not exactly the same as the dispersion from the FEM model. How is the dispersion being used by the LLE? I would have expected that using the dispersion from the FEM model for each resonator mode would have been sufficient. Is the idea to smooth the FEM-derived dispersion?

**Comment by DanHickstein** [comment]
(also, the dashed orange "fit" line is not seen in the graph in the iPython notebook)

**Comment by gregmoille** [comment]
Actually the LLE fit the Dint from the list of resonance from the FEM, using a spline function. The idea behind is to be able to extrapolate to solve a domain which is larger than the FEM simulation (for instance spending up the FEM once normal dispersion and wont change, but of interest for LLE accuracy) . The discrepancy I think should be minimal but there might be better function than spline to fit it

**Comment by DanHickstein** [comment]
Ah, okay, this makes sense. The spline seems to do a reasonable job.
