### ISSUE TITLE
Steady state solver example

### ISSUE THREAD

**Issue by zlnewman** [gregmoille/pyLLE#42]
Hey Gregory,
We're interesting to try using the steady state solver function of pyLLE. I've tried using the example from the 2019 arXiv paper and there seem to be some issues.  For example, it's difficult to define simulation parameters like the pump detuning or the initial solution parameters (like beta). Could you provide an example for the steady state solver?
Thanks,
Zach

**Comment by gregmoille** [comment]
He Zach! 

Glad to hear you’re using it. Yeah it has been quite a while I haven’t touch the steady state as it I always found the result to bot always be accurate compared to the temporal solver. 
I’ll come up with an up to date example shortly (hopefully within a week). Hope this timeline works for you. 

Cheers

Greg

**Comment by zlnewman** [comment]
Hey Greg!
Thanks for the quick reply. Not rush on updating the code, we seem to have the temporal solver running pretty smoothly now. Initially I thought that the steady state solver might be a convenient way to search for a set of parameters that would produce a soliton state, but the temporal solution runs reasonably quickly so perhaps that’s not the case. At any rate, I think we’ll continue to use the code (it’s very convenient; really nice work!), so if you have any insider tips on best practices for simulating microcombs let us know.

On an unrelated note, we have a job opening at Octave at the moment; do you have any interest in working in a small company? We’re just getting started developing a microcombs as a commercial product but we’re excited to really push on this effort in the coming year. We’d love to have a call with you sometime in the next couple weeks either way. We’ve all been working on all the same programs in different capacities for several years now, it would be fantastic to catch up in person (via the wonders of the internet).

Hope you have a nice weekend.
Zach

**Comment by gregmoille** [comment]
Sure happy to discuss whenever you want! Maybe we could discuss independently of this github issue. feel free to email me at gmoille@umd.edu or my nist email address.
