### ISSUE TITLE
Raman Shift

### ISSUE THREAD

**Issue by tristanmelton** [gregmoille/pyLLE#47]
The addition of Raman / soliton recoil, Ω, from ω_r= D1+ (D2/D1)Ω would be super useful, even as just a generalized parameter. I'm looking into implementing it myself too but I thought I'd bring it up here too.

**Comment by gregmoille** [comment]
Hey sorry for the super long delay replying. 
The recoil form the dispersion is already implemented given it uses the complete integrated dispersion, hence account for the odd dispersion term creating a shift of the center of mass of the DKS from the soliton along (DW mediated effect). 
For the Raman effect, that's a bit more complicated as it is a built-up effect that depends on the previous time-step (mathematically through the integral). Also, I focus mostly on SiN and as far as I know, the Raman parameter are not that well understood to create an accurate model. 
But if you come up with a ½ split Fourier step compatible solver to include the Raman effect, feel free to make a commit request, that would be great addition for the community
