### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by noor2323M** [gregmoille/pyLLE#48]
× python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [66 lines of output]
      Warning: 'classifiers' should be a list, got type 'tuple'
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib
      creating build\lib\pyLLE
      copying pyLLE\_analyzedisp.py -> build\lib\pyLLE
      copying pyLLE\_llesolver.py -> build\lib\pyLLE
      copying pyLLE\__init__.py -> build\lib\pyLLE
      running egg_info
      writing pyLLE.egg-info\PKG-INFO
      writing dependency_links to pyLLE.egg-info\dependency_links.txt
      writing requirements to pyLLE.egg-info\requires.txt
      writing top-level names to pyLLE.egg-info\top_level.txt
      reading manifest file 'pyLLE.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'pyLLE.egg-info\SOURCES.txt'
      copying pyLLE\ComputeLLE.jl -> build\lib\pyLLE
      C:\Users\my\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!

              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.

              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************

      !!
        self.initialize_options()
      installing to build\bdist.win-amd64\wheel
      running install
      running install_lib
      creating build\bdist.win-amd64
      creating build\bdist.win-amd64\wheel
      creating build\bdist.win-amd64\wheel\pyLLE
      copying build\lib\pyLLE\ComputeLLE.jl -> build\bdist.win-amd64\wheel\.\pyLLE
      copying build\lib\pyLLE\_analyzedisp.py -> build\bdist.win-amd64\wheel\.\pyLLE
      copying build\lib\pyLLE\_llesolver.py -> build\bdist.win-amd64\wheel\.\pyLLE
      copying build\lib\pyLLE\__init__.py -> build\bdist.win-amd64\wheel\.\pyLLE
      running install_egg_info
      Copying pyLLE.egg-info to build\bdist.win-amd64\wheel\.\pyLLE-4.1.1-py3.12.egg-info
      running install_scripts
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      ----------
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyLLE
  Running setup.py clean for pyLLE
Failed to build pyLLE
ERROR: Could not build wheels for pyLLE, which is required to install pyproject.toml-based projects

**Comment by noor2323M** [comment]
I am facing this issue while pip installing the package, please suggest the work around or ways to resolve it, Thanks!

**Comment by gregmoille** [comment]
Solve the issue for #49 #50 

The install actually worked all good, just the Julia package installed failed. Previously `import pyLLE` should have worked even if the `pip install` was failing as the installed worked up to the python process

It is a windows issue, and the Julia packaged needs to be installed manually. The commit 6982c3d goes in detail how to explain it
