### ISSUE TITLE
Failed to intsall pyLLE 4.1version

### ISSUE THREAD

**Issue by ZhimingShi** [gregmoille/pyLLE#51]
hi, I try to intsall pyLLE 4.1 vesion on windows, it failed, but I can pip install pyLLE 4.0 version. I followed yesterday's instructions to manually install julia，then pip install pyLLE 4.1, It still fails to install.
![image](https://github.com/gregmoille/pyLLE/assets/121110294/6aec818e-6a52-46a6-9021-3e1d1ac4fd5d)

**Comment by gregmoille** [comment]
Please don't reopen a issue when it is on the same one than #50 

I have tried on 2 different machine, it works with the 4.1.2 version. Also note the [reply](https://github.com/gregmoille/pyLLE/issues/48#issuecomment-1906163112) in the original issue #48. The error is not an error on the pip install and pyLLE is still install. I would advise you to remove it `pip uninstall pyLLE` and reinstall it. No matter, it should work which you could easy check with `python3 -c "import pyLLE"` and should exit without error
